### ISSUE TITLE
cmd redeclared in this block

### ISSUE THREAD

**Issue by importnil** [martingallagher/gawp#6]
I get this error trying to get main (and final) package:

go get -u github.com/martingallagher/gawp
`#` github.com/martingallagher/gawp
C:\GoSpace\src\github.com\martingallagher\gawp\cmd_windows.go:5: cmd redeclared in this block
        previous declaration at C:\GoSpace\src\github.com\martingallagher\gawp\cmd_unix.go:5

I'm using standard cmd. Windows 10 x64, Go 1.4.2 windows/amd64.

**Comment by martingallagher** [comment]
Apologies for the delayed response, I didn't receive a notification for this issue. I'll look at this ASAP (as soon as I get access to a Windows machine). Cheers!
